# Generated by Django 5.2.17 on 2026-09-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_remove_portfolioprofile_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_highlights_title",
            field=models.CharField(
                blank=True, default="Quick Portfolio Highlights", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_highlights_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_stats",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of stat highlights: [{'value': '1,000+', 'label': 'Production Users', 'icon': 'fas fa-users'}]",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="hero_stat_1_icon",
            field=models.CharField(blank=True, default="fas fa-users", max_length=50),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="hero_stat_1_label",
            field=models.CharField(
                blank=True, default="Production Users", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="hero_stat_1_value",
            field=models.CharField(blank=True, default="1,000+", max_length=50),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="hero_stat_2_icon",
            field=models.CharField(blank=True, default="fas fa-id-card", max_length=50),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="hero_stat_2_label",
            field=models.CharField(
                blank=True, default="ID Cards Processed", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="hero_stat_2_value",
            field=models.CharField(blank=True, default="136K+", max_length=50),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="hero_stat_3_icon",
            field=models.CharField(
                blank=True, default="fas fa-cloud-download-alt", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="hero_stat_3_label",
            field=models.CharField(
                blank=True, default="Cards Downloaded", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="hero_stat_3_value",
            field=models.CharField(blank=True, default="86K+", max_length=50),
        ),
    ]
